### ISSUE TITLE
Postgres Helm Chart

### ISSUE THREAD

**Issue by da721wol** [Involute1/CAD_GymApp#4]

**Comment by drescherflo** [comment]
Maybe it's better to user CockroachDB. This SQL-Database is built specifically for use within kubernetes and comes with helm charts created by the vendor itself.
The Java code should not change since Cockroach uses the postregs jdbc driver (see https://www.cockroachlabs.com/docs/cockroachcloud/quickstart?filters=local&filters=java)
Perhaps we don't even have to selfhost the db and use Cockroach's service instead. This depends on the pricing (and flexibility when it comes to the different enterpise levels), but there's a free plan.
I think this could reduce the time spend on configuring the SQL-Db significantly.

**Comment by drescherflo** [comment]
Working HA-Postgres for each service since 3cba64a
